// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

function positiveInteger (value) {
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const DR_PLAN_STRUCTURAL_EDIT_FIELDS = new Set([
  'enginetype',
  'enginebindingtype',
  'enginebindingid',
  'targetvmname',
  'targetzoneid',
  'targetstorageref',
  'targetcomputeref',
  'targetcpunumber',
  'targetcpuspeed',
  'targetmemory',
  'targetboottype',
  'targetbootmode',
  'targetrootdiskcontroller',
  'targetdatadiskcontroller',
  'targetiothreadsenabled',
  'targetiopolicy',
  'targetnetworkref',
  'targetfolderpath',
  'diskmappingsjson',
  'mappingjson'
])

export function resolveTargetComputeSizingValue (resolvedValue, existingValue, preserveExisting) {
  const resolved = positiveInteger(resolvedValue)
  if (resolved) return resolved
  return preserveExisting ? positiveInteger(existingValue) : undefined
}

export function resolveDrSourceDiskType (details = {}, path = '') {
  const explicit = String(details.sourceType || details.diskType || '').toLowerCase()
  if (explicit) return explicit
  const poolType = String(details.storagePoolType || details.poolType || '').toLowerCase()
  if (poolType.includes('rbd') || path.startsWith('rbd:') || path.startsWith('/dev/rbd/')) return 'rbd'
  if (path.startsWith('/dev/')) return 'block'
  return path ? 'file' : ''
}

export function resolveDrSourceDiskFormat (details = {}, path = '', kvmSource = false) {
  const explicit = String(details.format || details.sourceFormat || '').toLowerCase()
  if (explicit) return explicit
  const type = resolveDrSourceDiskType(details, path)
  if (type === 'rbd' || type === 'block') return 'raw'
  return type === 'file' && kvmSource ? 'qcow2' : ''
}

export function buildChangedPlanPayload (current = {}, baseline = {}) {
  return Object.keys(current).reduce((changed, key) => {
    if (JSON.stringify(current[key]) !== JSON.stringify(baseline[key])) {
      changed[key] = current[key]
    }
    return changed
  }, {})
}

export function requiresSourceHardwareRefresh (plan = {}, changedFields) {
  if (changedFields && !Object.keys(changedFields).some(key => DR_PLAN_STRUCTURAL_EDIT_FIELDS.has(key))) {
    return false
  }
  const planDirection = String(plan.direction || '').toUpperCase()
  let mapping = {}
  try {
    mapping = typeof plan.mappingjson === 'string'
      ? JSON.parse(plan.mappingjson || '{}')
      : (plan.mappingjson || {})
  } catch (error) {
    return planDirection.includes('ABLESTACK') || planDirection.startsWith('KVM_')
  }
  const mappingDirection = String(mapping.direction || '').toUpperCase()
  const sourceIsKvm = planDirection.includes('ABLESTACK') || planDirection.startsWith('KVM_') ||
    mappingDirection.startsWith('KVM_')
  if (!sourceIsKvm) {
    return false
  }
  const disks = mapping.disks || mapping.diskMappings || mapping.volumes || mapping.volumeMappings || []
  const hasIncompleteSourceStorageContract = Array.isArray(disks) && disks.some(disk => {
    const source = disk?.source || {}
    const sourcePath = source.path || source.vmdkPath || disk.sourcePath || disk.sourcepath || ''
    const sourceType = source.type || source.sourceType || disk.sourceType || disk.sourcetype || ''
    const sourceFormat = source.format || source.sourceFormat || disk.sourceFormat || disk.sourceformat || ''
    return Boolean(sourcePath) && (!sourceType || !sourceFormat)
  })
  if (hasIncompleteSourceStorageContract) {
    return true
  }
  const hardware = mapping?.source?.hardware || {}
  return Boolean(hardware.errorCode || hardware.errorcode)
}

export function updateAutoGeneratedDiskNames (rows = [], oldTargetVmName, newTargetVmName) {
  const oldPrefix = oldTargetVmName || 'dr-target'
  const newPrefix = newTargetVmName || 'dr-target'
  return rows.map((row, index) => {
    const oldAutomaticName = `${oldPrefix}-disk-${index}`
    if (row.targetDiskName && row.targetDiskName !== oldAutomaticName) {
      return row
    }
    return Object.assign({}, row, { targetDiskName: `${newPrefix}-disk-${index}` })
  })
}

export function findActiveDrRun (runs = [], predicate = () => false) {
  return (runs || []).find(run => run && run.id && predicate(run)) || null
}

export function buildActiveDrRunQuery (planId) {
  return {
    planid: planId,
    page: 1,
    pagesize: 20
  }
}
