#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOOK_OUTPUT_DIR="${HOOK_OUTPUT_DIR:-/usr/openv/netbackup/bin}"
CONFIG_OUTPUT_DIR="${CONFIG_OUTPUT_DIR:-/etc/ablestack/netbackup}"
SECRET_OUTPUT_DIR="${SECRET_OUTPUT_DIR:-/etc/ablestack/netbackup/secrets}"
PRE_HELPER_PATH="${PRE_HELPER_PATH:-/usr/share/cloudstack-common/scripts/vm/hypervisor/kvm/ablestack_netbackup_bpstart_notify.sh}"
POST_HELPER_PATH="${POST_HELPER_PATH:-/usr/share/cloudstack-common/scripts/vm/hypervisor/kvm/ablestack_netbackup_bpend_notify.sh}"
HOOK_LOG_PATH="${HOOK_LOG_PATH:-/var/log/netbackup-cloudstack-hook.log}"
SECRET_CIPHER="${SECRET_CIPHER:-aes-256-cbc}"
NETBACKUP_BP_CONF_PATH="${NETBACKUP_BP_CONF_PATH:-/usr/openv/netbackup/bp.conf}"
NETBACKUP_SERVICE_NAME="${NETBACKUP_SERVICE_NAME:-netbackup}"

POLICY_NAME=""
SCHEDULE_NAME=""
VM_INCLUDE=""
VM_EXCLUDE=""
MAX_INCREMENTAL_CHAIN=""
MOLD_URL=""
ADMIN_APIKEY=""
ADMIN_SECRETKEY=""
ENCRYPTION_PASSPHRASE=""
CONFIG_SCOPE=""

usage() {
  cat <<EOF
Usage: $(basename "$0")

Interactive generator for NetBackup policy hook files and config files.

Default output targets:
  Hook files   -> /usr/openv/netbackup/bin
  Config files -> /etc/ablestack/netbackup
  Secret files -> /etc/ablestack/netbackup/secrets

Environment overrides:
  HOOK_OUTPUT_DIR
  CONFIG_OUTPUT_DIR
  SECRET_OUTPUT_DIR
  PRE_HELPER_PATH
  POST_HELPER_PATH
  HOOK_LOG_PATH
  SECRET_CIPHER
  NETBACKUP_BP_CONF_PATH
  NETBACKUP_SERVICE_NAME
EOF
}

fail() {
  printf '%s\n' "$*" >&2
  exit 1
}

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

set_bp_conf_value() {
  local file_path="$1"
  local key="$2"
  local value="$3"

  if grep -Eq "^[[:space:]]*${key}[[:space:]]*=" "${file_path}"; then
    sed -i'' -E "s|^[[:space:]]*${key}[[:space:]]*=.*$|${key} = ${value}|" "${file_path}"
  else
    printf '%s = %s\n' "${key}" "${value}" >> "${file_path}"
  fi
}

prompt_value() {
  local var_name="$1"
  local prompt_text="$2"
  local default_value="${3:-}"
  local value=""

  if [[ -n "${default_value}" ]]; then
    read -r -p "${prompt_text} [${default_value}]: " value
    value="${value:-${default_value}}"
  else
    read -r -p "${prompt_text}: " value
  fi

  printf -v "${var_name}" '%s' "${value}"
}

prompt_secret_value() {
  local var_name="$1"
  local prompt_text="$2"
  local value=""
  read -r -s -p "${prompt_text}: " value
  printf '\n'
  printf -v "${var_name}" '%s' "${value}"
}

validate_name() {
  local name="$1"
  local label="$2"

  [[ -n "${name}" ]] || fail "${label} is required."
  [[ "${name}" != *"/"* ]] || fail "${label} must not contain '/'."
}

validate_positive_integer() {
  local value="$1"
  local label="$2"

  [[ "${value}" =~ ^[1-9][0-9]*$ ]] || fail "${label} must be a positive integer."
}

backup_existing_file() {
  local target="$1"
  [[ -f "${target}" ]] || return 0
  local backup_target="${target}.bak.$(date '+%Y%m%d%H%M%S')"
  mv "${target}" "${backup_target}"
  printf 'Backed up existing file: %s -> %s\n' "${target}" "${backup_target}"
}

copy_existing_file_backup() {
  local target="$1"
  [[ -f "${target}" ]] || return 0
  local backup_target="${target}.bak.$(date '+%Y%m%d%H%M%S')"
  cp -p "${target}" "${backup_target}"
  printf 'Backed up existing file: %s -> %s\n' "${target}" "${backup_target}"
}

write_pre_hook() {
  local target="$1"
  local filename_comment="$2"

  backup_existing_file "${target}"
  cat > "${target}" <<EOF
#!/bin/sh

# Generated by netbackup_config.sh: ${filename_comment}

CLIENT="\${1:-}"
POLICY="\${2:-}"
SCHEDULE="\${3:-}"
TYPE="\${4:-}"

LOG="${HOOK_LOG_PATH}"
HELPER="${PRE_HELPER_PATH}"

log_line() {
  printf '%s %s\n' "\$(date '+%F %T')" "\$1" >> "\$LOG" 2>&1
}

if [ \$# -lt 4 ]; then
  log_line "PRE invalid-args argc=\$# client=\$CLIENT policy=\$POLICY schedule=\$SCHEDULE type=\$TYPE"
  exit 2
fi

if [ ! -x "\$HELPER" ]; then
  log_line "PRE helper-missing path=\$HELPER"
  exit 3
fi

log_line "PRE start client=\$CLIENT policy=\$POLICY schedule=\$SCHEDULE type=\$TYPE"
"\$HELPER" "\$POLICY" "\$SCHEDULE" "\$CLIENT" >> "\$LOG" 2>&1
RC=\$?
log_line "PRE end rc=\$RC client=\$CLIENT policy=\$POLICY schedule=\$SCHEDULE type=\$TYPE"
exit \$RC
EOF
  chmod 0755 "${target}"
}

write_post_hook() {
  local target="$1"
  local filename_comment="$2"

  backup_existing_file "${target}"
  cat > "${target}" <<EOF
#!/bin/sh

# Generated by netbackup_config.sh: ${filename_comment}

CLIENT="\${1:-}"
POLICY="\${2:-}"
SCHEDULE="\${3:-}"
TYPE="\${4:-}"
STATUS="\${5:-0}"

LOG="${HOOK_LOG_PATH}"
HELPER="${POST_HELPER_PATH}"

log_line() {
  printf '%s %s\n' "\$(date '+%F %T')" "\$1" >> "\$LOG" 2>&1
}

if [ \$# -lt 4 ]; then
  log_line "POST invalid-args argc=\$# client=\$CLIENT policy=\$POLICY schedule=\$SCHEDULE type=\$TYPE status=\$STATUS"
  exit 2
fi

if [ ! -x "\$HELPER" ]; then
  log_line "POST helper-missing path=\$HELPER"
  exit 3
fi

log_line "POST start client=\$CLIENT policy=\$POLICY schedule=\$SCHEDULE type=\$TYPE status=\$STATUS"
"\$HELPER" "\$POLICY" "\$SCHEDULE" "\$CLIENT" "\$STATUS" >> "\$LOG" 2>&1
RC=\$?
log_line "POST end rc=\$RC client=\$CLIENT policy=\$POLICY schedule=\$SCHEDULE type=\$TYPE status=\$STATUS"
exit \$RC
EOF
  chmod 0755 "${target}"
}

write_config_file() {
  local target="$1"

  backup_existing_file "${target}"
  cat > "${target}" <<EOF
VM_INCLUDE="$(printf '%s' "${VM_INCLUDE}")"
VM_EXCLUDE="$(printf '%s' "${VM_EXCLUDE}")"
MAX_INCREMENTAL_CHAIN=${MAX_INCREMENTAL_CHAIN}
MOLD_URL="$(printf '%s' "${MOLD_URL}")"
ADMIN_APIKEY="$(printf '%s' "${ADMIN_APIKEY}")"
EOF
  chmod 0600 "${target}"
}

write_encrypted_secret_file() {
  local target="$1"

  command_exists openssl || fail "openssl command is required to encrypt ADMIN_SECRETKEY."
  backup_existing_file "${target}"
  umask 077
  printf '%s' "${ADMIN_SECRETKEY}" | \
    ENCRYPTION_PASSPHRASE="${ENCRYPTION_PASSPHRASE}" \
    openssl enc -"${SECRET_CIPHER}" -pbkdf2 -salt -pass env:ENCRYPTION_PASSPHRASE -out "${target}"
  chmod 0600 "${target}"
}

apply_permissions() {
  if [[ -d "${CONFIG_OUTPUT_DIR}" ]]; then
    chown root:root "${CONFIG_OUTPUT_DIR}"
    chmod 700 "${CONFIG_OUTPUT_DIR}"
    find "${CONFIG_OUTPUT_DIR}" -maxdepth 1 -type f -name '*.conf' -exec chmod 600 {} \;
  fi
}

apply_netbackup_bp_conf() {
  if [[ ! -f "${NETBACKUP_BP_CONF_PATH}" ]]; then
    printf 'NetBackup bp.conf not found: %s\n' "${NETBACKUP_BP_CONF_PATH}"
    return 1
  fi

  copy_existing_file_backup "${NETBACKUP_BP_CONF_PATH}"

  set_bp_conf_value "${NETBACKUP_BP_CONF_PATH}" "BPSTART_TIMEOUT" "14400"
  set_bp_conf_value "${NETBACKUP_BP_CONF_PATH}" "BPEND_TIMEOUT" "3600"
  set_bp_conf_value "${NETBACKUP_BP_CONF_PATH}" "CLIENT_READ_TIMEOUT" "21600"
  set_bp_conf_value "${NETBACKUP_BP_CONF_PATH}" "CLIENT_CONNECT_TIMEOUT" "1800"
  set_bp_conf_value "${NETBACKUP_BP_CONF_PATH}" "SERVER_CONNECT_TIMEOUT" "1800"

  printf 'Updated NetBackup config: %s\n' "${NETBACKUP_BP_CONF_PATH}"
  return 0
}

restart_netbackup_service() {
  if command_exists systemctl; then
    systemctl restart "${NETBACKUP_SERVICE_NAME}"
    printf 'Restarted NetBackup service via systemctl: %s\n' "${NETBACKUP_SERVICE_NAME}"
    return 0
  fi

  if command_exists service; then
    service "${NETBACKUP_SERVICE_NAME}" restart
    printf 'Restarted NetBackup service via service: %s\n' "${NETBACKUP_SERVICE_NAME}"
    return 0
  fi

  printf 'NetBackup service restart command not found. Please restart manually: %s\n' "${NETBACKUP_SERVICE_NAME}"
}

collect_inputs() {
  printf 'Select configuration scope:\n'
  printf '  1. Apply to all schedules in one policy\n'
  printf '  2. Apply to a specific schedule in one policy\n'
  read -r -p "Enter scope (1 or 2): " CONFIG_SCOPE

  [[ "${CONFIG_SCOPE}" == "1" || "${CONFIG_SCOPE}" == "2" ]] || fail "Scope must be 1 or 2."

  prompt_value POLICY_NAME "POLICY_NAME"
  validate_name "${POLICY_NAME}" "POLICY_NAME"

  if [[ "${CONFIG_SCOPE}" == "2" ]]; then
    prompt_value SCHEDULE_NAME "SCHEDULE_NAME"
    validate_name "${SCHEDULE_NAME}" "SCHEDULE_NAME"
  fi

  prompt_value VM_INCLUDE "VM_INCLUDE" "*"
  prompt_value VM_EXCLUDE "VM_EXCLUDE" ""
  prompt_value MAX_INCREMENTAL_CHAIN "MAX_INCREMENTAL_CHAIN" "10"
  validate_positive_integer "${MAX_INCREMENTAL_CHAIN}" "MAX_INCREMENTAL_CHAIN"
  prompt_value MOLD_URL "MOLD_URL"
  prompt_value ADMIN_APIKEY "ADMIN_APIKEY"
  prompt_secret_value ADMIN_SECRETKEY "ADMIN_SECRETKEY"
  [[ -n "${ADMIN_SECRETKEY}" ]] || fail "ADMIN_SECRETKEY is required."

  prompt_secret_value ENCRYPTION_PASSPHRASE "Encryption passphrase for ADMIN_SECRETKEY"
  [[ -n "${ENCRYPTION_PASSPHRASE}" ]] || fail "Encryption passphrase is required."

  local confirm_passphrase=""
  prompt_secret_value confirm_passphrase "Confirm encryption passphrase"
  [[ "${ENCRYPTION_PASSPHRASE}" == "${confirm_passphrase}" ]] || fail "Encryption passphrases do not match."
}

generate_outputs() {
  mkdir -p "${HOOK_OUTPUT_DIR}" "${CONFIG_OUTPUT_DIR}" "${SECRET_OUTPUT_DIR}"

  local pre_hook_path=""
  local post_hook_path=""
  local config_path=""
  local secret_path=""
  local hook_name_suffix=""

  if [[ "${CONFIG_SCOPE}" == "1" ]]; then
    hook_name_suffix="${POLICY_NAME}"
    pre_hook_path="${HOOK_OUTPUT_DIR}/bpstart_notify.${POLICY_NAME}"
    post_hook_path="${HOOK_OUTPUT_DIR}/bpend_notify.${POLICY_NAME}"
    config_path="${CONFIG_OUTPUT_DIR}/${POLICY_NAME}.conf"
  else
    hook_name_suffix="${POLICY_NAME}.${SCHEDULE_NAME}"
    pre_hook_path="${HOOK_OUTPUT_DIR}/bpstart_notify.${POLICY_NAME}.${SCHEDULE_NAME}"
    post_hook_path="${HOOK_OUTPUT_DIR}/bpend_notify.${POLICY_NAME}.${SCHEDULE_NAME}"
    config_path="${CONFIG_OUTPUT_DIR}/${POLICY_NAME}.${SCHEDULE_NAME}.conf"
  fi

  secret_path="${SECRET_OUTPUT_DIR}/secret.enc"

  write_pre_hook "${pre_hook_path}" "bpstart_notify.${hook_name_suffix}"
  write_post_hook "${post_hook_path}" "bpend_notify.${hook_name_suffix}"
  write_config_file "${config_path}"
  write_encrypted_secret_file "${secret_path}"
  apply_permissions
  if apply_netbackup_bp_conf; then
    restart_netbackup_service
  else
    printf 'Skipped NetBackup service restart because bp.conf was not found.\n'
  fi

  printf '\nGenerated files:\n'
  printf '  PRE hook   : %s\n' "${pre_hook_path}"
  printf '  POST hook  : %s\n' "${post_hook_path}"
  printf '  Config     : %s\n' "${config_path}"
  printf '  Secret(enc): %s\n' "${secret_path}"
}

main() {
  if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
  fi

  collect_inputs
  generate_outputs
}

main "$@"
